### ISSUE TITLE
VarnishCon AMS 2016

### ISSUE THREAD

**Issue by huayra** [varnishcache/homepage#12]
Issue for discussing talks, format and anything related to the conference in Amsterdam on June 17th.

@varnishcache/c-developers might be interested in discussing the VDD as well.

**Comment by aondio** [comment]
Nice @huayra

**Comment by huayra** [comment]
- Workshops+VDD on Thursday, June 16th.

- Conference day on Friday June 17th.
 - http://varnishcon2016.eventbrite.com/

- Final agenda for VarnishConConference day, June 17th:
 - https://varnishcon2016.sched.org/mobile/
