### ISSUE TITLE
Make VMODs linkable targets

### ISSUE THREAD

**Issue by glennslaven** [varnishcache/homepage#2]
I was linking to a few of the VMODs when they had their own page, and I'd still like to be able to direct people to a specific VMOD easily. 

I've got a branch over here https://github.com/varnishcache/homepage/compare/master...glennslaven:linkto_vmods as an idea on how it could work with targets & highlighting the row. It should probably be done neater with proper classes and an included JS file rather than inline JS changing the style attribute on the row.

Here's a screenshot
![image](https://cloud.githubusercontent.com/assets/2200596/14578305/de289376-03c7-11e6-91e4-a60846878b33.png)

Is this something that would be helpful?

**Comment by bsdphk** [comment]
I don't mind us having per-VMOD pages, as long as we have a plan for how to maintain them.

My idea was to format the vmod.vcc file, like we do for docs, and use that (we already have the url of that in the JSON format) would that be enough or would you want more info ?

Should we ask VMOD maintainers to include a RST file in their repos and put its URL in the JSON ?

For github I guess we could default to the README if there is one ?

**Comment by glennslaven** [comment]
That would make sense, I don't imagine it would be asking too much of VMOD maintainers to have a file in the repo so it can be grabbed for here.

**Comment by glennslaven** [comment]
Ok, so I haven't tried pulling the READMEs off github but I've got a branch that generates a page for each VMOD https://github.com/varnishcache/homepage/compare/master...glennslaven:vmodpages

I'm not 100% sure on using the READMEs, I think their formats are a bit too variable to include in a page.  I like the idea of asking for a rst file to include though, that could work.  `vmod_description.rst` or something like that. If we kept the name standardised then they wouldn't have to put a link to it, the build script could just go look for `repourl + "vmod_description.rst"`.

**Comment by bsdphk** [comment]
I agree that the READMEs were not a feasible way.

As I said in the pull request, instead I have made it possible to declare a documentation URL in the JSON which appear in a new column in the table, and I have redirected all the old urls to the table.
