### ISSUE TITLE
Decide the future of the mailing lists

### ISSUE THREAD

**Issue by espebra** [varnishcache/homepage#44]
I'll create this issue to get a discussion around the future of the mailing lists. The server currently running [the mailing lists](http://www.varnish-cache.org/lists/mailman/listinfo) will be shut down 15th of September 2017. This is due to the data center shutting down. Some alternatives are to migrate the lists to another mailman setup, migrate the lists to some other mailing list service or remain shut off/down.

**Comment by nigoroll** [comment]
we (UPLEX) volunteer to host a mailman. Getting access to the current setup would be helpful

**Comment by denisbr** [comment]
@nigoroll We can arrange with export / dump of the current setup. Tell us what you want exported.

**Comment by nigoroll** [comment]
continuing off-gh with @denisbr and @espebra

**Comment by bsdphk** [comment]
mailing lists now run by UPLEX (much appreciated!)
