### ISSUE TITLE
one canonical url, 301 the others

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/homepage#47]
saving from irc:

We respond with 200 to all permutations allowed by `https?://(?:www\.)?\.varnish-cache\.org` (tls or not, www or not - at least, idk if there are more urls accepted by our server)

To avoid being punished for duplicate content, we should define one primary url and 301 all others (keeping the path).

**Comment by nigoroll** [comment]
assigned to phk because he owns the server, if anyone else can look after this, please do

**Comment by bsdphk** [comment]
I'll happily share this responsibilty with anybody with more webmaster clue than me

**Comment by nigoroll** [comment]
done. As discussed with @bsdphk on irc, we will not force people to https, though
