### ISSUE TITLE
Clean up links about old versions, and clarify "the latest release"

### ISSUE THREAD

**Issue by slimhazard** [varnishcache/homepage#72]
The current v-c.o navigation section doesn't have a link to documentation for 6.2, but it has doc links to 6.1, 6.0, 5.2, 5.1 and 4.1.

On [v-c.o/docs/](https://varnish-cache.org/docs/index.html) ("Varnish Documentation"), all of 6.2, 6.1 and 6.0 are described as "the latest release". That's not possible; when the definite article is used with a superlative adjective, as in "the latest", it can only designate one thing.

Suggestions:

"The latest release" refers to the most recent semi-annual release, currently 6.2.

The v-c.o navigation section links to docs for: trunk, latest release, and supported (LTS) releases. Currently that would look like:

[trunk](https://varnish-cache.org/docs/trunk/index.html) [6.2](https://varnish-cache.org/docs/6.2/index.html) [6.0](https://varnish-cache.org/docs/6.0/index.html) [4.1](https://varnish-cache.org/docs/4.1/index.html)

Maybe there could be a brief explanation:

[trunk](https://varnish-cache.org/docs/trunk/index.html) [6.2 (latest)](https://varnish-cache.org/docs/6.2/index.html) [6.0 (supported)](https://varnish-cache.org/docs/6.0/index.html) [4.1 (supported)](https://varnish-cache.org/docs/4.1/index.html)

Remember that the "Documentation" link just above that list links to a more comprehensive list of doc links for previous versions, so we're not losing anything.

**Comment by bsdphk** [comment]
Go for it!

**Comment by slimhazard** [comment]
bugwash: do the "brief explanation" version, with an "older versions" link to the docs page

Will change "the latest" to refer only to 6.2, and 4.1 is no longer "supported".
