### ISSUE TITLE
Broken links need to be fixed. 404s make our users unhappy.

### ISSUE THREAD

**Issue by huayra** [varnishcache/homepage#9]
There is a huge number of broken links currently in varnish-cache.org and many users have asked for us to bring those back. Google has also noticed a rather high rise of 404s and has advised we fix this.

In the previous site, which now has its home on http://old.varnish-cache.org/ we had a [a couple of thousand links](https://github.com/varnishcache/homepage/files/232327/urllist_2016-04-12.txt) as of 2016-04-12, the day before the move to the new site. 

On the new site we have a few hundred links, so it is obvious that quite a few of these links are returning 404 to our users. Some of these URLs like everything going to /forum will be made available on a static copy with the corresponding redirect, just like what we have with the Trac Wiki . Others will be gone for good.

In the new site we have removed vmod/ and utility/ any future changes like the one proposed in #4 will not be problematic. So we need to redirect traffic for the most obvious ones.

**Explanation**
I'll write pseudo-code so you can turn it into beautiful Varnish regexp, based on the following logic:
- & means all the variants that need to point to a resource
- > means the resource all variants should point at
- () which mark exceptions

**Redirects within the site**
Links within the site that can be redirected directly and even wildcarded:
- vmod & vmod/\* & vmods?\* > vmods/
- utility & utility/\* & utilities/ & utilities?\* > extras/ 
- twitter & twitter?\* > support/
- project & project/\* > /
- unstable-releases/ & content/varnish-cache-\* > releases/ (except for 403 and 412 below)

Specific links within the site that need to be mapped individually:
- content/varnish-cache-403 > releases/rel4.0.3.html
- content/varnish-cache-412 > releases/rel4.1.2.html
- installation/freebsd > releases/install_freebsd.html
- installation/ubuntu > releases/install_ubuntu.html
- installation/debian > releases/install_debian.html
- installation/redhat > releases/install_redhat.html

**Redirects to links outside www. but within the domain**
**Planet**
Here are a few links that need to be redirected outside of the site:
- planet/ & planet/?\* > https://planet.varnish-cache.org

**From www. to old.**
redirecting to from www. to old. on the following links:
- https://www.varnish-cache.org/vug10 > https://old.varnish-cache.org/vug10
- https://www.varnish-cache.org/vug9 > https://old.varnish-cache.org/vug9
- https://www.varnish-cache.org/vug8 > https://old.varnish-cache.org/vug8
- https://www.varnish-cache.org/vug7 > https://old.varnish-cache.org/vug7
- https://www.varnish-cache.org/vug6 > https://old.varnish-cache.org/vug6
- https://www.varnish-cache.org/vug6-report > https://old.varnish-cache.org/vug6-report
- https://www.varnish-cache.org/vug5 > https://old.varnish-cache.org/vug5
- https://www.varnish-cache.org/vug5-report > https://old.varnish-cache.org/vug5-report

**Forum**
- forum/ & forum/1 > https://old.varnish-cache.org/forum/1
- forum/\* > https://old.varnish-cache.org/forum/*

All links pointing to the forum should be the respective resource in old. so that the content is available now. once we get the static copy of it we can change the redirect to "ForumArchive" internally in the site and kill the redirect to old.

**Static files**
An extensive list with the content linked from different pages (slides from VUGs, vcl examples) within the site and that is currently available in old. and with the same list as it should be in www. is available in this files (https links):
[urllist_w-www_2016-04-22.txt](https://github.com/varnishcache/homepage/files/232497/urllist_w-www_2016-04-22.txt)
[urllist_w-old_2016-04-22.txt](https://github.com/varnishcache/homepage/files/232498/urllist_w-old_2016-04-22.txt)

**Other improvements:**
Previously a link to a resource in the Wiki would work regardless of whether you typed wiki/ or trac/ or trac/wiki/ and this does not woirk in the new site since wiki/ gives a 404 and trac/ shows nothing, leaving trac/wiki as the only real option. At the very least we should make the following:
- wiki/ & wiki/\* & trac/ & trac/\* > trac/wiki/

Making sure that we also redirect the \* so that i.e. this (and any other wiki resource) works: wiki/VCLExamples & trac/VCLExamples > trac/wiki/VCLExamples

**Comment by bsdphk** [comment]
Thanks for the list Ruben, that must have taken a lot of time...

Just for anybody else listening in here, I'll repeat what I already talked with you about:

We're not going to resurrect every single possible URL than anybody might have ever used, that would pollute our namespace going forward.

Instead we 'recover' links which are clearly in use, as we go.

So far I have dealt with the VMOD pages (see the other issues/pull comments)

I've added 301's for the four /installation urls

The /planet links were already pointed to the other site, I've pointed /forum likewise now.

**Comment by bsdphk** [comment]
I have added a wildcard 301 from "^/utility" to "/extras/"

**Comment by bsdphk** [comment]
I have pointed "^/comment" at the old server.

**Comment by bsdphk** [comment]
I rewrite "docs/master" to "docs/trunk"

What about rss.xml ?

**Comment by bsdphk** [comment]
Added:

content/varnish-cache-403 > releases/rel4.0.3.html
content/varnish-cache-412 > releases/rel4.1.2.html

**Comment by bsdphk** [comment]
I have added the wiki -> trac/wiki redirect, but we SERIOUSLY need to study what people read there and make sure it is still connected to reality.

I have moved the ArchtectNotes from the wiki into my random outbursts

**Comment by rezan** [comment]
Old trac changeset links are 404s. Random example:

https://www.varnish-cache.org/trac/changeset/cfb309cad60e0239bc7168082d73b4ab6b53744a/

**Comment by bsdphk** [comment]
Yes, I know.  I don't think we'll be doing anything about those.

**Comment by huayra** [comment]
Thanks. Can already see things working much better.

Could you please make that 301 "^/utilit"instead of "^/utility" so we cover all utility and utilities* cases?

If you have the VCL somewhere I could also send a PR or send the updated file.

**Comment by huayra** [comment]
The content links are still not working. Could we add a "^/content/varnish-cache-" pointing to releases/ and be done with it?

**Comment by huayra** [comment]
Wiki clean-up is a major task that needs to be approached properly.

I have a plan for that and it includes going through the whole thing, curating its content, making a collection of properly supported VCL examples/templates and integration snippets and better documentation. 

I will not get into details now, but expect to see issues popping up here on GitHub next week.

**Comment by huayra** [comment]
Adding a new issue on rss.xml

**Comment by bsdphk** [comment]
Forum is now snapshot'ed.

**Comment by bsdphk** [comment]
Only thing we access from old server now is planet

**Comment by huayra** [comment]
Most of this is now fixed. Last thing needing to move is the Planet. Is there any traffic to it these days?

**Comment by bsdphk** [comment]
I have 410'ed /planet.
