### ISSUE TITLE
Extras inconsistency

### ISSUE THREAD

**Issue by akuznecov** [varnishcache/homepage#90]
Hello,

I want to add my CLI tool to the Extras page and Misc category.
But it seems repository content is out of sync with the site.
There are lot of entities of https://varnish-cache.org/extras/index.html are missing on
https://github.com/varnishcache/homepage/blob/master/R1/source/extras/extras-misc.csv

So how do I proceed?

B.R.

**Comment by bsdphk** [comment]
I think only extras.csv is actually used, so add to that.

It looks like Ruben planned to extras into multiple tables, but never carried through...
